events {}

http {
    server {
        listen 80;
        server_name .localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name .localhost;

        ssl_certificate /Users/sadovnychyi/.localhost.crt;
        ssl_certificate_key /Users/sadovnychyi/.localhost.key;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 443;
            proxy_set_header X-AppEngine-Https on;
        }
    }
}
